template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "lush1252"
__REPO__ = "lang-lut"
__UND2C__ = "lut"
__UNDEFINED__ = "Lushootseed"
__UND__ = "lut"
