template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "lush1252"
__REPO__ = "lang-lut"
__UND2C__ = "lut"
__UNDEFINED__ = "Lushootseed"
__UND__ = "lut"
