template = "https://github.com/giellalt/template-lang-und"
rev_id = 255
template_sha = "b36832e6713c79f483aee143e866d6cad5dec90e"

[replacements]
__GLOTTOLOG_ID__ = "lush1252"
__REPO__ = "lang-lut"
__UND2C__ = "lut"
__UNDEFINED__ = "Lushootseed"
__UND__ = "lut"
